apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo-ns
type: Opaque
data:
  # Base64 encoded values (username: admin, password: password123)
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQxMjM=