apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo-ns
type: Opaque
data:
  # Connection string: mongodb://admin:password123@mongodb-service:27017
  mongo-uri: bW9uZ29RiYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGItc2VydmljZToyNzAxNw==